LESDIR=../../../..

include $(LESDIR)/makefiles/StandardHeader.mk

LIBNAME=PROJbase

CFILES=projHelloWorld.c

OFILES=projHelloWorld.o

include $(LESDIR)/makefiles/Component.mk
include $(LESDIR)/makefiles/StandardFooter.mk
