SUBDIR=varint usrint ossiint ossiissue usrOssiJobLog

all: $(SUBDIR)

$(SUBDIR) : FRC
	cd "$(MAKEDIR)\$@"
	$(MAKE) -nologo -fmakefile.nt $(TARGET)

clean : 
	$(MAKE) -nologo -fmakefile.nt TARGET=clean

install: hinstall
	$(MAKE) -nologo -fmakefile.nt TARGET=install

hinstall :
	$(MAKE) -nologo -fmakefile.nt TARGET=hinstall

FRC:
