LESDIR=../../..

include $(LESDIR)/makefiles/StandardHeader.mk

LIBNAME=USRint

OFILES=MOCAversion.o \
       usrTestUsrCommand.o

include $(LESDIR)/makefiles/Component.mk
include $(LESDIR)/makefiles/StandardFooter.mk
