LESDIR=../../..

include $(LESDIR)/makefiles/StandardHeader.mk

LIBNAME=ossiint

OFILES=MOCAinitialize.o \
MOCAversion.o \
ossiExecuteMOCAAndCache.o \
ossiExecuteRemoteRetrieve.o \
ossiExpandVarsInString.o \
ossiTransposeResult.o \
ossiURLDecode.o \
ossiURLEncode.o \
usrOssiConvertPointerToType.o \
usrOssiGetErrorCode.o \
usrOssiGetTimestamp.o \
usrOssiTransposeResult.o 

include $(LESDIR)/makefiles/Component.mk
include $(LESDIR)/makefiles/StandardFooter.mk
