LESDIR=../../..

include $(LESDIR)/makefiles/StandardHeader.mk

LIBNAME=VARint

OFILES=MOCAversion.o \
       varTestVarCommand.o

include $(LESDIR)/makefiles/Component.mk
include $(LESDIR)/makefiles/StandardFooter.mk
