SUBDIR=hello

all: $(SUBDIR)

$(SUBDIR): FRC
	cd "$(MAKEDIR)\$@"
	$(MAKE) -nologo -fmakefile.nt $(TARGET)

clean:
	$(MAKE) -nologo -fmakefile.nt TARGET=clean

install:
	$(MAKE) -nologo -fmakefile.nt TARGET=install

FRC:
